# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beaconSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeaconSettings(object):
    def setupUi(self, BeaconSettings):
        BeaconSettings.setObjectName("BeaconSettings")
        BeaconSettings.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(BeaconSettings)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setMouseTracking(False)
        self.buttonBox.setAcceptDrops(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(BeaconSettings)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 331, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.periodLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.periodLabel.setObjectName("periodLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.periodLabel)
        self.tDevicesLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.tDevicesLabel.setObjectName("tDevicesLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tDevicesLabel)
        self.periodLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.periodLineEdit.setObjectName("periodLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.periodLineEdit)
        self.tDevicesLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tDevicesLineEdit.setObjectName("tDevicesLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tDevicesLineEdit)

        self.retranslateUi(BeaconSettings)
        self.buttonBox.accepted.connect(BeaconSettings.accept)
        self.buttonBox.rejected.connect(BeaconSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(BeaconSettings)

    def retranslateUi(self, BeaconSettings):
        _translate = QtCore.QCoreApplication.translate
        BeaconSettings.setWindowTitle(_translate("BeaconSettings", "Dialog"))
        self.periodLabel.setText(_translate("BeaconSettings", "Period"))
        self.tDevicesLabel.setText(_translate("BeaconSettings", "Test Devices"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BeaconSettings = QtWidgets.QDialog()
    ui = Ui_BeaconSettings()
    ui.setupUi(BeaconSettings)
    BeaconSettings.show()
    sys.exit(app.exec_())
