# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dbSettings(object):
    def setupUi(self, dbSettings):
        dbSettings.setObjectName("dbSettings")
        dbSettings.setWindowModality(QtCore.Qt.WindowModal)
        dbSettings.resize(416, 325)
        self.buttonBox = QtWidgets.QDialogButtonBox(dbSettings)
        self.buttonBox.setGeometry(QtCore.QRect(60, 280, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(dbSettings)
        self.formLayoutWidget.setGeometry(QtCore.QRect(29, 19, 371, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.databaseNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.databaseNameLabel.setObjectName("databaseNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.databaseNameLabel)
        self.databaseNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.databaseNameLineEdit.setObjectName("databaseNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.databaseNameLineEdit)
        self.userLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.userLabel.setObjectName("userLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.userLabel)
        self.userLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userLineEdit.setObjectName("userLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userLineEdit)
        self.hostLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.hostLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hostLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.portLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.portLineEdit)
        self.portLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.portLabel)

        self.retranslateUi(dbSettings)
        self.buttonBox.accepted.connect(dbSettings.accept)
        self.buttonBox.rejected.connect(dbSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(dbSettings)

    def retranslateUi(self, dbSettings):
        _translate = QtCore.QCoreApplication.translate
        dbSettings.setWindowTitle(_translate("dbSettings", "Database Settings"))
        self.databaseNameLabel.setText(_translate("dbSettings", "Database Name"))
        self.userLabel.setText(_translate("dbSettings", "User"))
        self.hostLabel.setText(_translate("dbSettings", "Host"))
        self.passwordLabel.setText(_translate("dbSettings", "Password"))
        self.portLineEdit.setText(_translate("dbSettings", "5432"))
        self.portLabel.setText(_translate("dbSettings", "Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dbSettings = QtWidgets.QDialog()
    ui = Ui_dbSettings()
    ui.setupUi(dbSettings)
    dbSettings.show()
    sys.exit(app.exec_())
